### ISSUE TITLE
Any doc for this project ?

### ISSUE THREAD

**Issue by jeason1997** [TheHologram/unity-console#1]
![image](https://user-images.githubusercontent.com/10192062/40009969-07906252-57d6-11e8-97ac-a9955a5139a8.png)

**Comment by TheHologram** [comment]
I realize this is really old but commenting for completion.  I haven't logged in for 4 years so.  No documentation as its mostly a personal project that I've published.  I think its useful so released it.

The idea for this function is that you can provide the python context and gameobject and python function.  Not sure if this function was fully finished or not.  I think the idea was to avoid OnGUI callbacks for options that did not need it so you would use this for that.  

Normally create_gui_behavior was used and gameobject would be created.


I think in python this would appear as 

class PyBehaviorClass:
   def __init__(self):
       pass
   def OnGUI(self):
       pass

behavior = unity_util.add_gui_behavior(gameObject, PyBehaviorClass)
